# Generated by Django 5.1.6 on 2025-03-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myNotesApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
